name: Actualizador Autonomo 24/7 LotoPro RD

on:
  schedule:
    - cron: '*/5 13-23 * * *'
    - cron: '*/5 0-4 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  actualizar:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar codigo
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: |
          pip install beautifulsoup4 openpyxl pandas

      - name: Ejecutar Rastreador
        working-directory: ./Loteria ag
        run: |
          python actualizador_automatico.py

      - name: Guardar cambios si hay sorteos nuevos
        run: |
          git config --global user.name "LotoPro Bot"
          git config --global user.email "bot@lotopro.rd"
          git add "Loteria ag/datos_en_vivo.js" "Loteria ag/sorteos_hoy.json" "Loteria ag/historial_loterias.json" "Loteria ag/datos_historial.js" "Loteria ag/Recientes.xlsx"
          git diff --staged --quiet || (git commit -m "Auto-actualizacion de sorteos en vivo [skip ci]" && git push)
